sudo: required
language: generic
services:
  - docker

before_install: 
  - docker build -t robingautam/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true robingautam/react-test npm test

after_success:
  - docker build -t robin/multi-client ./client
  - docker build -t robin/multi-nginx ./nginx
  - docker build -t robin/multi-server ./server
  - docker build -t robin/multi-worker ./worker
  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push into docker hub
  - docker push rbngtm1/multi-client
  - docker push rbngtm1/multi-nginx
  - docker push rbngtm1/multi-server
  - docker push rbngtm1/multi-worker

