sudo: required
language: generic
services:
  - docker

before_install: 
  - docker build -t robingautam/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true robingautam/react-test npm test

after_success:
  - docker build -t rbngtm1/multi-client ./client
  - docker build -t rbngtm1/multi-nginx ./nginx
  - docker build -t rbngtm1/multi-server ./server
  - docker build -t rbngtm1/multi-worker ./worker
  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push into docker hub.
  - docker push rbngtm1/multi-client
  - docker push rbngtm1/multi-nginx
  - docker push rbngtm1/multi-server
  - docker push rbngtm1/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker-container
  env: MultiDockerContainer-env
  bucket_name: elasticbeanstalk-us-east-1-222385317864
  bucket_path: docker-multi
  on: 
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

